### 데이터 결측치 처리

## 기후 데이터_최신화_2025
평균기온  
평균최고기온  
최고기온  
평균최저기온  
최저기온  
평균 풍속  
최대 순간 풍속  
최대 순간 풍속 풍향  
강수량합

In [ ]:
import pandas as pd

climate = pd.read_csv('../../data/raw/climate(기후데이터)/기후데이터.csv')

In [3]:
climate.head()

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
0,강원특별자치도 강릉시,11.43,16.54,34.04,6.76,-14.34,2.11,21.01,205.21,1782.79,...,1427.71,11.73,17.07,34.30,6.82,-17.54,2.05,24.97,253.80,1436.07
1,강원특별자치도 고성군,9.46,13.88,32.68,5.44,-16.24,3.92,28.48,223.46,3358.02,...,1940.28,9.94,14.34,32.80,5.82,-20.96,3.92,32.58,219.54,1783.10
2,강원특별자치도 동해시,12.05,17.40,28.43,7.40,-13.13,2.40,20.33,198.13,1217.00,...,1314.33,12.77,18.37,35.87,7.80,-16.67,2.15,23.23,258.37,1489.83
3,강원특별자치도 삼척시,12.02,17.28,35.30,7.38,-12.87,1.82,20.50,171.57,1559.17,...,1072.92,12.30,17.98,35.93,7.30,-16.53,1.68,25.80,227.92,1337.08
4,강원특별자치도 속초시,12.85,17.40,34.30,8.60,-10.45,1.45,27.70,187.25,2670.50,...,1936.50,13.15,17.95,36.65,8.80,-16.50,1.35,20.40,236.60,1660.50

In [6]:
climate.loc[:,climate.isnull().sum().index]

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
0,강원특별자치도 강릉시,11.43,16.54,34.04,6.76,-14.34,2.11,21.01,205.21,1782.79,...,1427.71,11.73,17.07,34.30,6.82,-17.54,2.05,24.97,253.80,1436.07
1,강원특별자치도 고성군,9.46,13.88,32.68,5.44,-16.24,3.92,28.48,223.46,3358.02,...,1940.28,9.94,14.34,32.80,5.82,-20.96,3.92,32.58,219.54,1783.10
2,강원특별자치도 동해시,12.05,17.40,28.43,7.40,-13.13,2.40,20.33,198.13,1217.00,...,1314.33,12.77,18.37,35.87,7.80,-16.67,2.15,23.23,258.37,1489.83
3,강원특별자치도 삼척시,12.02,17.28,35.30,7.38,-12.87,1.82,20.50,171.57,1559.17,...,1072.92,12.30,17.98,35.93,7.30,-16.53,1.68,25.80,227.92,1337.08
4,강원특별자치도 속초시,12.85,17.40,34.30,8.60,-10.45,1.45,27.70,187.25,2670.50,...,1936.50,13.15,17.95,36.65,8.80,-16.50,1.35,20.40,236.60,1660.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,충청북도 제천시,11.70,17.80,34.27,6.57,-15.53,1.30,16.30,312.63,1425.33,...,1321.83,12.27,18.60,35.43,6.93,-19.07,1.15,18.53,301.33,1594.00
159,충청북도 증평군,12.60,18.20,35.20,7.50,-15.40,1.50,21.80,346.20,1451.00,...,1238.50,13.30,19.10,35.60,7.90,-18.10,1.30,19.30,354.60,1557.50
160,충청북도 진천군,11.90,17.90,35.15,6.90,-15.60,1.50,21.85,302.65,1700.75,...,1281.25,13.05,19.25,36.20,7.60,-18.90,1.45,18.15,273.85,1582.00
161,충청북도 청주시,12.24,18.30,35.08,7.22,-16.90,1.36,15.92,115.18,1464.34,...,1138.60,13.22,19.28,35.70,8.02,-18.34,1.48,16.72,248.48,1878.34
162,충청북도 충주시,11.43,17.93,34.60,5.60,-19.23,1.53,16.67,255.93,1525.67,...,1383.67,11.93,18.63,35.70,6.07,-19.77,1.40,18.27,253.90,1635.50

In [8]:
climate.isnull().sum()

SGG_NAME                0
AVG_TEMP_20            18
AVG_MAX_TEMP_20        19
MAX_TEMP_20            17
AVG_MIN_TEMP_20        19
MIN_TEMP_20            17
AVG_WIND_SPD_20        22
MAX_GUST_SPD_20        17
MAX_GUST_DIR_DEG_20    17
TOTAL_RAIN_20          17
AVG_TEMP_21            20
AVG_MAX_TEMP_21        20
MAX_TEMP_21            17
AVG_MIN_TEMP_21        20
MIN_TEMP_21            17
AVG_WIND_SPD_21        21
MAX_GUST_SPD_21        17
MAX_GUST_DIR_DEG_21    17
TOTAL_RAIN_21          17
AVG_TEMP_22            18
AVG_MAX_TEMP_22        18
MAX_TEMP_22            17
AVG_MIN_TEMP_22        18
MIN_TEMP_22            17
AVG_WIND_SPD_22        19
MAX_GUST_SPD_22        17
MAX_GUST_DIR_DEG_22    17
TOTAL_RAIN_22          17
AVG_TEMP_23            24
AVG_MAX_TEMP_23        24
MAX_TEMP_23            17
AVG_MIN_TEMP_23        24
MIN_TEMP_23            17
AVG_WIND_SPD_23        27
MAX_GUST_SPD_23        17
MAX_GUST_DIR_DEG_23    17
TOTAL_RAIN_23          17
dtype: int64

In [11]:
list(climate.loc[climate.isnull().any(axis=1),'SGG_NAME'])

['강원특별자치도 태백시',
 '경상남도 고성군',
 '경상남도 의령군',
 '경상북도 고령군',
 '광주광역시 북구',
 '광주광역시 서구',
 '대구광역시 남구',
 '대구광역시 달서구',
 '대구광역시 수성구',
 '대구광역시 중구',
 '대전광역시 대덕구',
 '대전광역시 동구',
 '대전광역시 서구',
 '대전광역시 유성구',
 '부산광역시 동구',
 '부산광역시 부산진구',
 '부산광역시 사상구',
 '부산광역시 사하구',
 '부산광역시 서구',
 '부산광역시 수영구',
 '부산광역시 영도구',
 '부산광역시 중구',
 '울산광역시 중구',
 '전라남도 담양군',
 '전라남도 목포시',
 '전라남도 영암군',
 '전라남도 함평군',
 '충청남도 계룡시',
 '충청남도 금산군',
 '충청남도 부여군',
 '충청남도 서산시',
 '충청남도 예산군',
 '충청남도 천안시',
 '충청북도 보은군',
 '충청북도 영동군']

In [16]:
len(climate.loc[climate.isnull().any(axis=1),'SGG_NAME'])

35

총 35개 시군구에서 결측이 발견되었다. 종관기상과 겹치는 시군구를 탐색합니다.

In [ ]:
import pandas as pd
asos = pd.read_csv('../../data/climate(기후데이터)/보조_기후데이터_시_군_구_수정_컬럼명변경.csv', encoding='cp949')

In [32]:
asos.head()

,지점,시군구,지점명,일시,AVG_TEMP,MIN_TEMP,MAX_TEMP,AVG_MIN_TEMP,AVG_MAX_TEMP,평균 해면기압(hPa),TOTAL_RAIN,일 최다 강수량(mm),평균 상대습도(%),합계 일조시간(hr),일조율(%),합계 일사량(MJ/m2),평균 풍속(m/s),최다 풍향(16방위),합계 소형 증발량(mm),합계 대형 증발량(mm)
0,강원도,속초시,속초,2020,13.3,-11.3,35.1,9.3,17.5,1015.3,2085.8,214.6,61.7,2447.9,54.85,NaN,2.1,270,NaN,NaN
1,강원도,속초시,속초,2021,13.2,-16.1,33.8,9.2,17.4,1015.5,1199.7,83.5,64.5,2478.1,55.77,NaN,2.0,270,NaN,NaN
2,강원도,속초시,속초,2022,12.9,-12.5,35.5,8.8,17.1,1015.4,1637.3,119.4,61.8,2488.1,55.86,0.00,2.0,270,NaN,NaN
3,강원도,속초시,속초,2023,13.6,-16.0,36.6,9.5,17.8,1015.4,1768.8,368.7,63.5,2379.8,55.50,NaN,1.9,270,NaN,NaN
4,강원도,춘천시,북춘천,2020,11.4,-18.5,35.8,5.9,17.8,1016.8,1561.4,188.5,72.5,2281.7,51.12,5226.28,1.3,200,1285.2,900.1

In [39]:
asos['지점'].unique()

array(['강원도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시',
       '세종특별자치시', '울산광역시', '전라남도', '전북특별자치도', '충청남도', '충청북도', '제주특별자치도'],
      dtype=object)

In [43]:
col = set()
for l in climate['SGG_NAME'].unique():
    col.add(l.split()[0])
print(col)

{'울산광역시', '충청북도', '전라남도', '충청남도', '전북특별자치도', '경상남도', '경상북도', '대구광역시', '부산광역시', '제주특별자치도', '세종특별자치시', '광주광역시', '강원특별자치도', '대전광역시'}

In [ ]:
asos.loc[asos['지점'] == '강원도','지점'] = '강원특별자치도'

In [45]:
asos.head()

,지점,시군구,지점명,일시,AVG_TEMP,MIN_TEMP,MAX_TEMP,AVG_MIN_TEMP,AVG_MAX_TEMP,평균 해면기압(hPa),TOTAL_RAIN,일 최다 강수량(mm),평균 상대습도(%),합계 일조시간(hr),일조율(%),합계 일사량(MJ/m2),평균 풍속(m/s),최다 풍향(16방위),합계 소형 증발량(mm),합계 대형 증발량(mm)
0,강원특별자치도,속초시,속초,2020,13.3,-11.3,35.1,9.3,17.5,1015.3,2085.8,214.6,61.7,2447.9,54.85,NaN,2.1,270,NaN,NaN
1,강원특별자치도,속초시,속초,2021,13.2,-16.1,33.8,9.2,17.4,1015.5,1199.7,83.5,64.5,2478.1,55.77,NaN,2.0,270,NaN,NaN
2,강원특별자치도,속초시,속초,2022,12.9,-12.5,35.5,8.8,17.1,1015.4,1637.3,119.4,61.8,2488.1,55.86,0.00,2.0,270,NaN,NaN
3,강원특별자치도,속초시,속초,2023,13.6,-16.0,36.6,9.5,17.8,1015.4,1768.8,368.7,63.5,2379.8,55.50,NaN,1.9,270,NaN,NaN
4,강원특별자치도,춘천시,북춘천,2020,11.4,-18.5,35.8,5.9,17.8,1016.8,1561.4,188.5,72.5,2281.7,51.12,5226.28,1.3,200,1285.2,900.1

In [50]:
asos['SGG_NAME'] = asos['지점'].str.cat(asos['시군구'], sep=' ')

In [51]:
asos.head()

,지점,시군구,지점명,일시,AVG_TEMP,MIN_TEMP,MAX_TEMP,AVG_MIN_TEMP,AVG_MAX_TEMP,평균 해면기압(hPa),...,일 최다 강수량(mm),평균 상대습도(%),합계 일조시간(hr),일조율(%),합계 일사량(MJ/m2),평균 풍속(m/s),최다 풍향(16방위),합계 소형 증발량(mm),합계 대형 증발량(mm),SGG_NAME
0,강원특별자치도,속초시,속초,2020,13.3,-11.3,35.1,9.3,17.5,1015.3,...,214.6,61.7,2447.9,54.85,NaN,2.1,270,NaN,NaN,강원특별자치도 속초시
1,강원특별자치도,속초시,속초,2021,13.2,-16.1,33.8,9.2,17.4,1015.5,...,83.5,64.5,2478.1,55.77,NaN,2.0,270,NaN,NaN,강원특별자치도 속초시
2,강원특별자치도,속초시,속초,2022,12.9,-12.5,35.5,8.8,17.1,1015.4,...,119.4,61.8,2488.1,55.86,0.00,2.0,270,NaN,NaN,강원특별자치도 속초시
3,강원특별자치도,속초시,속초,2023,13.6,-16.0,36.6,9.5,17.8,1015.4,...,368.7,63.5,2379.8,55.50,NaN,1.9,270,NaN,NaN,강원특별자치도 속초시
4,강원특별자치도,춘천시,북춘천,2020,11.4,-18.5,35.8,5.9,17.8,1016.8,...,188.5,72.5,2281.7,51.12,5226.28,1.3,200,1285.2,900.1,강원특별자치도 춘천시

In [53]:
## asos와 겹치는 시군구명 정리
org_lst = list(climate.loc[climate.isnull().any(axis=1),'SGG_NAME'])

In [54]:
asos_lst = asos['SGG_NAME'].unique()

asos_org_lst = [x for x in asos_lst if x in org_lst]
asos_org_lst

['강원특별자치도 태백시',
 '경상남도 의령군',
 '광주광역시 북구',
 '대전광역시 유성구',
 '부산광역시 중구',
 '울산광역시 중구',
 '전라남도 목포시',
 '충청남도 서산시',
 '충청남도 천안시',
 '충청남도 부여군',
 '충청남도 금산군',
 '충청북도 영동군',
 '충청북도 보은군']

## 데이터 확인

In [ ]:
import pandas as pd

climate_edit = pd.read_csv('../../data/climate(기후데이터)/기후데이터_수정_0807.csv')

In [131]:
climate_edit.head()

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
0,강원특별자치도 강릉시,11.43,16.54,34.04,6.76,-14.34,2.11,21.01,205.21,1782.79,...,1427.71,11.73,17.07,34.30,6.82,-17.54,2.05,24.97,253.80,1436.07
1,강원특별자치도 고성군,9.46,13.88,32.68,5.44,-16.24,3.92,28.48,223.46,3358.02,...,1940.28,9.94,14.34,32.80,5.82,-20.96,3.92,32.58,219.54,1783.10
2,강원특별자치도 동해시,12.05,17.40,28.43,7.40,-13.13,2.40,20.33,198.13,1217.00,...,1314.33,12.77,18.37,35.87,7.80,-16.67,2.15,23.23,258.37,1489.83
3,강원특별자치도 삼척시,12.02,17.28,35.30,7.38,-12.87,1.82,20.50,171.57,1559.17,...,1072.92,12.30,17.98,35.93,7.30,-16.53,1.68,25.80,227.92,1337.08
4,강원특별자치도 속초시,12.85,17.40,34.30,8.60,-10.45,1.45,27.70,187.25,2670.50,...,1936.50,13.15,17.95,36.65,8.80,-16.50,1.35,20.40,236.60,1660.50

In [132]:
climate_edit.isnull().sum()

SGG_NAME                0
AVG_TEMP_20            12
AVG_MAX_TEMP_20        13
MAX_TEMP_20            11
AVG_MIN_TEMP_20        13
MIN_TEMP_20            11
AVG_WIND_SPD_20        14
MAX_GUST_SPD_20        17
MAX_GUST_DIR_DEG_20    17
TOTAL_RAIN_20          11
AVG_TEMP_21            13
AVG_MAX_TEMP_21        13
MAX_TEMP_21            11
AVG_MIN_TEMP_21        13
MIN_TEMP_21            11
AVG_WIND_SPD_21        15
MAX_GUST_SPD_21        17
MAX_GUST_DIR_DEG_21    17
TOTAL_RAIN_21          11
AVG_TEMP_22            12
AVG_MAX_TEMP_22        12
MAX_TEMP_22            11
AVG_MIN_TEMP_22        12
MIN_TEMP_22            11
AVG_WIND_SPD_22        13
MAX_GUST_SPD_22        17
MAX_GUST_DIR_DEG_22    17
TOTAL_RAIN_22          11
AVG_TEMP_23            14
AVG_MAX_TEMP_23        14
MAX_TEMP_23            11
AVG_MIN_TEMP_23        14
MIN_TEMP_23            11
AVG_WIND_SPD_23        17
MAX_GUST_SPD_23        17
MAX_GUST_DIR_DEG_23    17
TOTAL_RAIN_23          11
dtype: int64

* 결측된 시군구만 확인

In [133]:
list(climate_edit.loc[climate_edit.isnull().any(axis=1),'SGG_NAME'])

['강원특별자치도 태백시',
 '경상남도 고성군',
 '경상남도 의령군',
 '경상북도 고령군',
 '광주광역시 서구',
 '대구광역시 남구',
 '대구광역시 달서구',
 '대구광역시 수성구',
 '대구광역시 중구',
 '대전광역시 대덕구',
 '대전광역시 동구',
 '대전광역시 서구',
 '부산광역시 동구',
 '부산광역시 부산진구',
 '부산광역시 사상구',
 '부산광역시 사하구',
 '부산광역시 서구',
 '부산광역시 수영구',
 '부산광역시 영도구',
 '부산광역시 중구',
 '울산광역시 중구',
 '전라남도 담양군',
 '전라남도 목포시',
 '전라남도 영암군',
 '전라남도 함평군',
 '충청남도 계룡시',
 '충청남도 금산군',
 '충청남도 예산군']

In [134]:
#강원특별자치도 태백시
## 인접 시군구 3개 평균

## 인접 시군구 딕셔너리
adjacent_dict = {
    '강원특별자치도 태백시': ['강원특별자치도 삼척시', '강원특별자치도 정선군', '강원특별자치도 영월군'],
    '경상남도 고성군': ['경상남도 사천시', '경상남도 통영시', '경상남도 진주시'],
    '경상남도 의령군': ['경상남도 진주시', '경상남도 함안군', '경상남도 창녕군'],
    '경상북도 고령군': ['대구광역시 달성군', '경상북도 성주군', '경상남도 합천군'],
    '광주광역시 서구': ['광주광역시 동구', '광주광역시 북구', '광주광역시 남구'],
    '대구광역시 남구': ['대구광역시 중구', '대구광역시 수성구', '대구광역시 달서구'],
    '대구광역시 달서구': ['대구광역시 남구', '대구광역시 중구', '대구광역시 서구'],
    '대구광역시 수성구': ['대구광역시 중구', '대구광역시 남구', '대구광역시 동구'],
    '대구광역시 중구': ['대구광역시 북구', '대구광역시 서구', '대구광역시 남구'],
    '대전광역시 대덕구': ['대전광역시 동구', '대전광역시 중구', '대전광역시 서구'],
    '대전광역시 동구': ['대전광역시 대덕구', '대전광역시 중구', '충청북도 옥천군'],
    '대전광역시 서구': ['대전광역시 중구', '대전광역시 유성구', '대전광역시 대덕구'],
    '부산광역시 동구': ['부산광역시 중구', '부산광역시 영도구', '부산광역시 부산진구'],
    '부산광역시 부산진구': ['부산광역시 동구', '부산광역시 연제구', '부산광역시 사상구'],
    '부산광역시 사상구': ['부산광역시 북구', '부산광역시 부산진구', '부산광역시 사하구'],
    '부산광역시 사하구': ['부산광역시 사상구', '부산광역시 강서구', '부산광역시 남구'],
    '부산광역시 서구': ['부산광역시 중구', '부산광역시 동구', '부산광역시 사하구'],
    '부산광역시 수영구': ['부산광역시 해운대구', '부산광역시 연제구', '부산광역시 남구'],
    '부산광역시 영도구': ['부산광역시 중구', '부산광역시 동구', '부산광역시 남구'],
    '부산광역시 중구': ['부산광역시 동구', '부산광역시 서구', '부산광역시 영도구'],
    '울산광역시 중구': ['울산광역시 남구', '울산광역시 북구', '울산광역시 동구'],
    '전라남도 담양군': ['광주광역시 북구', '전라남도 순천시', '전라남도 장성군'],
    '전라남도 목포시': ['전라남도 무안군', '전라남도 신안군', '전라남도 영암군'],
    '전라남도 영암군': ['전라남도 목포시', '전라남도 무안군', '전라남도 장흥군'],
    '전라남도 함평군': ['전라남도 나주시', '전라남도 무안군', '전라남도 영광군'],
    '충청남도 계룡시': ['충청남도 논산시', '충청남도 금산군', '대전광역시 유성구'],
    '충청남도 금산군': ['대전광역시 동구', '충청북도 옥천군', '충청남도 진천군'],
    '충청남도 예산군': ['충청남도 홍성군', '충청남도 당진시', '충청남도 아산시']
}

In [135]:
## 인접 시군의 평균으로 결측값이 있다면 채웁니다.
# def fill_with_neighbors_mean(row, target_col, neigh_dict, df):
#     if pd.isnull(row[target_col]):
#         neighbors = neigh_dict.get(row['SGG_NAME'], [])
#         neigh_vals = df[df['SGG_NAME'].isin(neighbors)][target_col]
#         mean_val = neigh_vals.mean()
#         return round(mean_val,1)
#     else:
#         return row[target_col]

def fill_with_neighbors_mean(row, target_col, neigh_dict, df):
    if pd.isnull(row[target_col]):
        neighbors = neigh_dict.get(row['SGG_NAME'], [])
        neigh_vals = df[df['SGG_NAME'].isin(neighbors)][target_col]
        # 결측이 아닌 값만 필터링
        valid_values = neigh_vals.dropna()
        if len(valid_values) > 0:
            return round(valid_values.mean(),1)
        else:
            # 모든 이웃값이 결측이면 원래 값 유지(NaN)
            return row[target_col]
    else:
        return row[target_col]

In [136]:
for target_col in climate_edit.columns:
    climate_edit[target_col] = climate_edit.apply(
        lambda row: fill_with_neighbors_mean(row, target_col, adjacent_dict, climate_edit), axis=1
    )

In [137]:
print(climate_edit.loc[climate_edit['SGG_NAME']=='강원특별자치도 태백시',:])

       SGG_NAME  AVG_TEMP_20  AVG_MAX_TEMP_20  MAX_TEMP_20  AVG_MIN_TEMP_20  \
13  강원특별자치도 태백시          9.6             15.0         34.9              4.9

    MIN_TEMP_20  AVG_WIND_SPD_20  MAX_GUST_SPD_20  MAX_GUST_DIR_DEG_20  \
13        -17.1              1.5             21.8                204.5

    TOTAL_RAIN_20  ...  TOTAL_RAIN_22  AVG_TEMP_23  AVG_MAX_TEMP_23  \
13         1530.1  ...         1088.9         10.0             15.8

    MAX_TEMP_23  AVG_MIN_TEMP_23  MIN_TEMP_23  AVG_WIND_SPD_23  \
13         33.3              4.6        -21.0              4.6

    MAX_GUST_SPD_23  MAX_GUST_DIR_DEG_23  TOTAL_RAIN_23
13             22.7                250.9         1525.8

[1 rows x 37 columns]

In [138]:
climate_edit.iloc[13:14,:]

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
13,강원특별자치도 태백시,9.6,15.0,34.9,4.9,-17.1,1.5,21.8,204.5,1530.1,...,1088.9,10.0,15.8,33.3,4.6,-21.0,4.6,22.7,250.9,1525.8

In [140]:
climate_edit.loc[climate_edit.isnull().any(axis=1), :]

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
64,대구광역시 남구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
## 대구광역시 남구에 대해 다시 진행
for target_col in climate_edit.columns:
    climate_edit[target_col] = climate_edit.apply(
        lambda row: fill_with_neighbors_mean(row, target_col, adjacent_dict, climate_edit), axis=1
    )

In [142]:
climate_edit.loc[climate_edit.isnull().any(axis=1), :]

Empty DataFrame
Columns: [SGG_NAME, AVG_TEMP_20, AVG_MAX_TEMP_20, MAX_TEMP_20, AVG_MIN_TEMP_20, MIN_TEMP_20, AVG_WIND_SPD_20, MAX_GUST_SPD_20, MAX_GUST_DIR_DEG_20, TOTAL_RAIN_20, AVG_TEMP_21, AVG_MAX_TEMP_21, MAX_TEMP_21, AVG_MIN_TEMP_21, MIN_TEMP_21, AVG_WIND_SPD_21, MAX_GUST_SPD_21, MAX_GUST_DIR_DEG_21, TOTAL_RAIN_21, AVG_TEMP_22, AVG_MAX_TEMP_22, MAX_TEMP_22, AVG_MIN_TEMP_22, MIN_TEMP_22, AVG_WIND_SPD_22, MAX_GUST_SPD_22, MAX_GUST_DIR_DEG_22, TOTAL_RAIN_22, AVG_TEMP_23, AVG_MAX_TEMP_23, MAX_TEMP_23, AVG_MIN_TEMP_23, MIN_TEMP_23, AVG_WIND_SPD_23, MAX_GUST_SPD_23, MAX_GUST_DIR_DEG_23, TOTAL_RAIN_23]
Index: []

[0 rows x 37 columns]

In [146]:
climate_edit.isnull().sum()

SGG_NAME               0
AVG_TEMP_20            0
AVG_MAX_TEMP_20        0
MAX_TEMP_20            0
AVG_MIN_TEMP_20        0
MIN_TEMP_20            0
AVG_WIND_SPD_20        0
MAX_GUST_SPD_20        0
MAX_GUST_DIR_DEG_20    0
TOTAL_RAIN_20          0
AVG_TEMP_21            0
AVG_MAX_TEMP_21        0
MAX_TEMP_21            0
AVG_MIN_TEMP_21        0
MIN_TEMP_21            0
AVG_WIND_SPD_21        0
MAX_GUST_SPD_21        0
MAX_GUST_DIR_DEG_21    0
TOTAL_RAIN_21          0
AVG_TEMP_22            0
AVG_MAX_TEMP_22        0
MAX_TEMP_22            0
AVG_MIN_TEMP_22        0
MIN_TEMP_22            0
AVG_WIND_SPD_22        0
MAX_GUST_SPD_22        0
MAX_GUST_DIR_DEG_22    0
TOTAL_RAIN_22          0
AVG_TEMP_23            0
AVG_MAX_TEMP_23        0
MAX_TEMP_23            0
AVG_MIN_TEMP_23        0
MIN_TEMP_23            0
AVG_WIND_SPD_23        0
MAX_GUST_SPD_23        0
MAX_GUST_DIR_DEG_23    0
TOTAL_RAIN_23          0
dtype: int64

In [147]:
climate_edit.dtypes

SGG_NAME                object
AVG_TEMP_20            float64
AVG_MAX_TEMP_20        float64
MAX_TEMP_20            float64
AVG_MIN_TEMP_20        float64
MIN_TEMP_20            float64
AVG_WIND_SPD_20        float64
MAX_GUST_SPD_20        float64
MAX_GUST_DIR_DEG_20    float64
TOTAL_RAIN_20          float64
AVG_TEMP_21            float64
AVG_MAX_TEMP_21        float64
MAX_TEMP_21            float64
AVG_MIN_TEMP_21        float64
MIN_TEMP_21            float64
AVG_WIND_SPD_21        float64
MAX_GUST_SPD_21        float64
MAX_GUST_DIR_DEG_21    float64
TOTAL_RAIN_21          float64
AVG_TEMP_22            float64
AVG_MAX_TEMP_22        float64
MAX_TEMP_22            float64
AVG_MIN_TEMP_22        float64
MIN_TEMP_22            float64
AVG_WIND_SPD_22        float64
MAX_GUST_SPD_22        float64
MAX_GUST_DIR_DEG_22    float64
TOTAL_RAIN_22          float64
AVG_TEMP_23            float64
AVG_MAX_TEMP_23        float64
MAX_TEMP_23            float64
AVG_MIN_TEMP_23        float64
MIN_TEMP_23            float64
AVG_WIND_SPD_23        float64
MAX_GUST_SPD_23        float64
MAX_GUST_DIR_DEG_23    float64
TOTAL_RAIN_23          float64
dtype: object

In [148]:
climate_edit.head()

,SGG_NAME,AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,TOTAL_RAIN_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
0,강원특별자치도 강릉시,11.43,16.54,34.04,6.76,-14.34,2.11,21.01,205.21,1782.79,...,1427.71,11.73,17.07,34.30,6.82,-17.54,2.05,24.97,253.80,1436.07
1,강원특별자치도 고성군,9.46,13.88,32.68,5.44,-16.24,3.92,28.48,223.46,3358.02,...,1940.28,9.94,14.34,32.80,5.82,-20.96,3.92,32.58,219.54,1783.10
2,강원특별자치도 동해시,12.05,17.40,28.43,7.40,-13.13,2.40,20.33,198.13,1217.00,...,1314.33,12.77,18.37,35.87,7.80,-16.67,2.15,23.23,258.37,1489.83
3,강원특별자치도 삼척시,12.02,17.28,35.30,7.38,-12.87,1.82,20.50,171.57,1559.17,...,1072.92,12.30,17.98,35.93,7.30,-16.53,1.68,25.80,227.92,1337.08
4,강원특별자치도 속초시,12.85,17.40,34.30,8.60,-10.45,1.45,27.70,187.25,2670.50,...,1936.50,13.15,17.95,36.65,8.80,-16.50,1.35,20.40,236.60,1660.50

In [ ]:
climate_edit.to_csv('../../processed/기후데이터.csv', index=False)