### 데이터 결측치 처리

## 대상 데이터
* 0으로 채우기

천 명 당 의료기관병상수  
총 병상 수  
보건복지시설 수(사회복지시설 수)  

체육시설수

## 기후 데이터
평균기온  
평균최고기온  
최고기온  
평균최저기온  
최저기온  
평균 풍속  
최대 순간 풍속  
최대 순간 풍속 풍향  
강수량합

In [4]:
import pandas as pd

num_beds_1000 = pd.read_csv('../data/health(보건)/천명당의료기관병상수.csv')
num_beds = pd.read_csv('../data/health(보건)/총병상수.csv')

## 보건복지 시설 수
num_welfare = pd.read_csv('../data/health(보건)/사회복지시설수.csv')

In [5]:
num_beds_1000.head()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
0,강원특별자치도 강릉시,12.5,12.4,11.8,11.3
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
2,강원특별자치도 동해시,15.9,14.5,14.6,14.3
3,강원특별자치도 삼척시,6.2,6.5,6.5,6.7
4,강원특별자치도 속초시,10.5,10.3,10.2,10.1

In [6]:
#sang_hos.loc[sang_hos['SGG_NAME'] == '부산광역시 부산진구',:]
print(num_beds_1000.isna().sum())
print(num_beds.isna().sum())

SGG_NAME           0
BED_PER_1000_20    2
BED_PER_1000_21    2
BED_PER_1000_22    2
BED_PER_1000_23    3
dtype: int64
SGG_NAME        0
BED_TOTAL_20    2
BED_TOTAL_21    2
BED_TOTAL_22    2
BED_TOTAL_23    2
dtype: int64

In [7]:
num_beds_1000[num_beds_1000['BED_PER_1000_23'].isnull()]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
6,강원특별자치도 양양군,NaN,NaN,NaN,NaN
63,대구광역시 군위군,0.4,0.4,0.4,NaN

In [8]:
num_beds[num_beds['SGG_NAME'] == '대구광역시 군위군']

     SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
63  대구광역시 군위군          10.0          10.0          10.0          10.0

* 대구광역시 군위군의 BED_PER_1000_23 컬럼 값은 22년도의 0.4로 동일하게 채웁니다.

In [9]:

num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']['BED_PER_1000_22']

63    0.4
Name: BED_PER_1000_22, dtype: float64

In [10]:
num_beds_1000.loc[num_beds_1000['SGG_NAME'] == '대구광역시 군위군', 'BED_PER_1000_23'] =  num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']['BED_PER_1000_22']

In [11]:
num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
63,대구광역시 군위군,0.4,0.4,0.4,0.4

In [12]:
## 나머지 값은 0으로 채웁니다.
num_beds_1000[num_beds_1000['BED_PER_1000_20'].isnull()]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
6,강원특별자치도 양양군,NaN,NaN,NaN,NaN

In [13]:
num_beds_1000.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    2
BED_PER_1000_21    2
BED_PER_1000_22    2
BED_PER_1000_23    2
dtype: int64

In [14]:

#num_beds_1000[num_beds_1000['BED_PER_1000_20'].isnull()]
num_beds_1000_zero = num_beds_1000.fillna(0)

In [15]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [16]:
num_beds_1000_zero.iloc[[1,6],:]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,0.0,0.0,0.0,0.0
6,강원특별자치도 양양군,0.0,0.0,0.0,0.0

In [17]:
num_beds_1000_zero.head()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
0,강원특별자치도 강릉시,12.5,12.4,11.8,11.3
1,강원특별자치도 고성군,0.0,0.0,0.0,0.0
2,강원특별자치도 동해시,15.9,14.5,14.6,14.3
3,강원특별자치도 삼척시,6.2,6.5,6.5,6.7
4,강원특별자치도 속초시,10.5,10.3,10.2,10.1

In [18]:
num_beds_1000_zero.tail()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
158,충청북도 제천시,17.8,16.8,16.0,15.5
159,충청북도 증평군,6.6,6.7,6.6,5.1
160,충청북도 진천군,10.9,10.1,10.3,10.4
161,충청북도 청주시,12.6,12.6,12.4,12.1
162,충청북도 충주시,12.5,13.4,13.6,13.9

In [19]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [20]:
## num_beds
num_beds.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    2
BED_TOTAL_21    2
BED_TOTAL_22    2
BED_TOTAL_23    2
dtype: int64

In [21]:
num_beds[num_beds['BED_TOTAL_20'].isnull()]

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
1  강원특별자치도 고성군           NaN           NaN           NaN           NaN
6  강원특별자치도 양양군           NaN           NaN           NaN           NaN

In [22]:
num_beds_zero = num_beds.fillna(0, axis=0)

In [23]:
num_beds_zero.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64

In [24]:
num_beds_zero.head()

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
0  강원특별자치도 강릉시        2660.0        2648.0        2499.0        2376.0
1  강원특별자치도 고성군           0.0           0.0           0.0           0.0
2  강원특별자치도 동해시        1439.0        1305.0        1308.0        1268.0
3  강원특별자치도 삼척시         406.0         412.0         412.0         420.0
4  강원특별자치도 속초시         872.0         853.0         848.0         827.0

In [25]:
num_beds_zero.tail()

     SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
158  충청북도 제천시        2364.0        2217.0        2097.0        2020.0
159  충청북도 증평군         244.0         244.0         245.0         192.0
160  충청북도 진천군         911.0         861.0         887.0         898.0
161  충청북도 청주시       10617.0       10699.0       10516.0       10352.0
162  충청북도 충주시        2630.0        2803.0        2825.0        2886.0

In [26]:
num_beds_1000.dtypes

SGG_NAME            object
BED_PER_1000_20    float64
BED_PER_1000_21    float64
BED_PER_1000_22    float64
BED_PER_1000_23    float64
dtype: object

In [27]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [28]:
num_beds_zero.dtypes

SGG_NAME         object
BED_TOTAL_20    float64
BED_TOTAL_21    float64
BED_TOTAL_22    float64
BED_TOTAL_23    float64
dtype: object

In [29]:
num_beds_zero = num_beds_zero.astype(dtype='int64', errors='ignore')

In [30]:
num_beds_zero.dtypes

SGG_NAME        object
BED_TOTAL_20     int64
BED_TOTAL_21     int64
BED_TOTAL_22     int64
BED_TOTAL_23     int64
dtype: object

In [31]:
num_beds_zero.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64

In [32]:
num_beds_zero.head()

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
0  강원특별자치도 강릉시          2660          2648          2499          2376
1  강원특별자치도 고성군             0             0             0             0
2  강원특별자치도 동해시          1439          1305          1308          1268
3  강원특별자치도 삼척시           406           412           412           420
4  강원특별자치도 속초시           872           853           848           827

In [33]:
num_beds_zero.to_csv('../processed/총병상수.csv', index=False)
num_beds_1000_zero.to_csv('../processed/천명당의료기관병상수.csv', index=False)

* 사회복지시설 수: 0으로 채우기

In [34]:
num_welfare.head()

      SGG_NAME  WELFARE_CNT_20  WELFARE_CNT_21  WELFARE_CNT_22  WELFARE_CNT_23
0  강원특별자치도 강릉시             2.0             2.0             2.0             2.0
1  강원특별자치도 고성군             NaN             NaN             NaN             1.0
2  강원특별자치도 동해시             3.0             3.0             2.0             2.0
3  강원특별자치도 삼척시             NaN             1.0             1.0             1.0
4  강원특별자치도 속초시             1.0             1.0             1.0             1.0

In [35]:
num_welfare.isnull().sum()

SGG_NAME           0
WELFARE_CNT_20    46
WELFARE_CNT_21    44
WELFARE_CNT_22    43
WELFARE_CNT_23    40
dtype: int64

In [36]:
num_welfare[num_welfare.isnull().any(axis=1)]

,SGG_NAME,WELFARE_CNT_20,WELFARE_CNT_21,WELFARE_CNT_22,WELFARE_CNT_23
1,강원특별자치도 고성군,NaN,NaN,NaN,1.0
3,강원특별자치도 삼척시,NaN,1.0,1.0,1.0
5,강원특별자치도 양구군,NaN,NaN,NaN,NaN
7,강원특별자치도 영월군,NaN,NaN,NaN,NaN
9,강원특별자치도 인제군,NaN,NaN,NaN,NaN
11,강원특별자치도 철원군,NaN,NaN,NaN,NaN
13,강원특별자치도 태백시,NaN,1.0,1.0,1.0
23,경상남도 밀양시,NaN,NaN,NaN,NaN
28,경상남도 진주시,NaN,NaN,NaN,2.0
31,경상남도 통영시,1.0,NaN,NaN,NaN
32,경상남도 하동군,NaN,NaN,1.0,1.0
38,경상북도 고령군,NaN,1.0,1.0,1.0
41,경상북도 문경시,NaN,NaN,NaN,NaN
42,경상북도 봉화군,NaN,NaN,NaN,NaN
43,경상북도 상주시,NaN,NaN,NaN,NaN
44,경상북도 성주군,NaN,NaN,1.0,1.0
46,경상북도 영덕군,NaN,NaN,NaN,NaN
50,경상북도 예천군,NaN,NaN,NaN,NaN
51,경상북도 울릉군,NaN,NaN,NaN,NaN
53,경상북도 의성군,NaN,NaN,NaN,NaN
54,경상북도 청도군,NaN,NaN,NaN,NaN
56,경상북도 칠곡군,NaN,NaN,NaN,NaN
59,광주광역시 남구,NaN,NaN,NaN,NaN
63,대구광역시 군위군,NaN,NaN,NaN,NaN
64,대구광역시 남구,NaN,NaN,NaN,NaN
71,대구광역시 중구,NaN,NaN,NaN,1.0
72,대전광역시 대덕구,NaN,NaN,NaN,NaN
99,전라남도 강진군,NaN,NaN,NaN,NaN
108,전라남도 보성군,NaN,NaN,NaN,NaN
112,전라남도 영광군,NaN,NaN,NaN,NaN
114,전라남도 완도군,NaN,NaN,NaN,NaN
115,전라남도 장성군,NaN,NaN,NaN,NaN
117,전라남도 진도군,NaN,NaN,NaN,NaN
124,전북특별자치도 남원시,NaN,NaN,NaN,NaN
127,전북특별자치도 순창군,NaN,NaN,NaN,NaN
130,전북특별자치도 임실군,NaN,NaN,NaN,NaN
134,전북특별자치도 진안군,NaN,NaN,NaN,NaN
139,충청남도 금산군,NaN,NaN,NaN,NaN
142,충청남도 보령시,NaN,NaN,NaN,NaN
143,충청남도 부여군,NaN,NaN,NaN,NaN
145,충청남도 서천군,NaN,NaN,NaN,NaN
147,충청남도 예산군,NaN,NaN,NaN,NaN
149,충청남도 청양군,NaN,NaN,NaN,NaN
151,충청남도 홍성군,1.0,1.0,NaN,NaN
153,충청북도 단양군,NaN,NaN,NaN,NaN
154,충청북도 보은군,NaN,NaN,NaN,NaN
155,충청북도 영동군,NaN,NaN,NaN,NaN
156,충청북도 옥천군,NaN,NaN,NaN,NaN

In [37]:
## 이 모든 값을 0으로 채웁니다.
num_welfare_zero = num_welfare.copy()
#print(num_welfare_zero.dtypes)
num_welfare_zero = num_welfare_zero.fillna(0)
#print(num_welfare_zero.dtypes)

In [38]:
num_welfare_zero.isnull().sum()

SGG_NAME          0
WELFARE_CNT_20    0
WELFARE_CNT_21    0
WELFARE_CNT_22    0
WELFARE_CNT_23    0
dtype: int64

In [39]:
num_welfare_zero[num_welfare.isnull().any(axis=1)]

,SGG_NAME,WELFARE_CNT_20,WELFARE_CNT_21,WELFARE_CNT_22,WELFARE_CNT_23
1,강원특별자치도 고성군,0.0,0.0,0.0,1.0
3,강원특별자치도 삼척시,0.0,1.0,1.0,1.0
5,강원특별자치도 양구군,0.0,0.0,0.0,0.0
7,강원특별자치도 영월군,0.0,0.0,0.0,0.0
9,강원특별자치도 인제군,0.0,0.0,0.0,0.0
11,강원특별자치도 철원군,0.0,0.0,0.0,0.0
13,강원특별자치도 태백시,0.0,1.0,1.0,1.0
23,경상남도 밀양시,0.0,0.0,0.0,0.0
28,경상남도 진주시,0.0,0.0,0.0,2.0
31,경상남도 통영시,1.0,0.0,0.0,0.0
32,경상남도 하동군,0.0,0.0,1.0,1.0
38,경상북도 고령군,0.0,1.0,1.0,1.0
41,경상북도 문경시,0.0,0.0,0.0,0.0
42,경상북도 봉화군,0.0,0.0,0.0,0.0
43,경상북도 상주시,0.0,0.0,0.0,0.0
44,경상북도 성주군,0.0,0.0,1.0,1.0
46,경상북도 영덕군,0.0,0.0,0.0,0.0
50,경상북도 예천군,0.0,0.0,0.0,0.0
51,경상북도 울릉군,0.0,0.0,0.0,0.0
53,경상북도 의성군,0.0,0.0,0.0,0.0
54,경상북도 청도군,0.0,0.0,0.0,0.0
56,경상북도 칠곡군,0.0,0.0,0.0,0.0
59,광주광역시 남구,0.0,0.0,0.0,0.0
63,대구광역시 군위군,0.0,0.0,0.0,0.0
64,대구광역시 남구,0.0,0.0,0.0,0.0
71,대구광역시 중구,0.0,0.0,0.0,1.0
72,대전광역시 대덕구,0.0,0.0,0.0,0.0
99,전라남도 강진군,0.0,0.0,0.0,0.0
108,전라남도 보성군,0.0,0.0,0.0,0.0
112,전라남도 영광군,0.0,0.0,0.0,0.0
114,전라남도 완도군,0.0,0.0,0.0,0.0
115,전라남도 장성군,0.0,0.0,0.0,0.0
117,전라남도 진도군,0.0,0.0,0.0,0.0
124,전북특별자치도 남원시,0.0,0.0,0.0,0.0
127,전북특별자치도 순창군,0.0,0.0,0.0,0.0
130,전북특별자치도 임실군,0.0,0.0,0.0,0.0
134,전북특별자치도 진안군,0.0,0.0,0.0,0.0
139,충청남도 금산군,0.0,0.0,0.0,0.0
142,충청남도 보령시,0.0,0.0,0.0,0.0
143,충청남도 부여군,0.0,0.0,0.0,0.0
145,충청남도 서천군,0.0,0.0,0.0,0.0
147,충청남도 예산군,0.0,0.0,0.0,0.0
149,충청남도 청양군,0.0,0.0,0.0,0.0
151,충청남도 홍성군,1.0,1.0,0.0,0.0
153,충청북도 단양군,0.0,0.0,0.0,0.0
154,충청북도 보은군,0.0,0.0,0.0,0.0
155,충청북도 영동군,0.0,0.0,0.0,0.0
156,충청북도 옥천군,0.0,0.0,0.0,0.0

In [40]:
## 시설 수는 int64로 저장
num_welfare_zero = num_welfare_zero.astype(dtype='int64', errors='ignore')

In [41]:
num_welfare_zero.isnull().sum()

SGG_NAME          0
WELFARE_CNT_20    0
WELFARE_CNT_21    0
WELFARE_CNT_22    0
WELFARE_CNT_23    0
dtype: int64

In [42]:
num_welfare_zero.dtypes

SGG_NAME          object
WELFARE_CNT_20     int64
WELFARE_CNT_21     int64
WELFARE_CNT_22     int64
WELFARE_CNT_23     int64
dtype: object

In [43]:
num_welfare_zero.head()

      SGG_NAME  WELFARE_CNT_20  WELFARE_CNT_21  WELFARE_CNT_22  WELFARE_CNT_23
0  강원특별자치도 강릉시               2               2               2               2
1  강원특별자치도 고성군               0               0               0               1
2  강원특별자치도 동해시               3               3               2               2
3  강원특별자치도 삼척시               0               1               1               1
4  강원특별자치도 속초시               1               1               1               1

In [44]:
num_welfare_zero.to_csv('../processed/사회복지시설수.csv', index=False)

## 휴양 및 문화
* 체육시설 수 : 결측치 0으로 처리

In [49]:
%pwd

'c:\\Users\\user\\Desktop\\project\\population-outflow\\notebooks'

In [50]:
num_sports = pd.read_csv('../data/recreation_culture(휴양및문화)/체육시설수.csv')
num_sports.head()

,SGG_NAME,SPORTS_FACILITIES_20,SPORTS_FACILITIES_21,SPORTS_FACILITIES_22,SPORTS_FACILITIES_23
0,강원특별자치도 강릉시,7.0,7.0,7.0,10.0
1,강원특별자치도 고성군,4.0,4.0,4.0,4.0
2,강원특별자치도 동해시,6.0,6.0,6.0,6.0
3,강원특별자치도 삼척시,4.0,5.0,5.0,5.0
4,강원특별자치도 속초시,5.0,5.0,5.0,5.0

In [51]:
num_sports.isnull().sum()

SGG_NAME                 0
SPORTS_FACILITIES_20    13
SPORTS_FACILITIES_21    14
SPORTS_FACILITIES_22    14
SPORTS_FACILITIES_23    14
dtype: int64

In [52]:
num_sports[num_sports.isnull().any(axis=1)]

,SGG_NAME,SPORTS_FACILITIES_20,SPORTS_FACILITIES_21,SPORTS_FACILITIES_22,SPORTS_FACILITIES_23
59,광주광역시 남구,NaN,NaN,NaN,NaN
67,대구광역시 동구,NaN,NaN,NaN,NaN
69,대구광역시 서구,NaN,NaN,NaN,NaN
71,대구광역시 중구,NaN,NaN,NaN,NaN
74,대전광역시 서구,NaN,NaN,NaN,NaN
80,부산광역시 남구,NaN,NaN,NaN,NaN
82,부산광역시 동래구,NaN,NaN,NaN,NaN
83,부산광역시 부산진구,NaN,NaN,NaN,NaN
84,부산광역시 북구,NaN,NaN,NaN,NaN
87,부산광역시 서구,NaN,NaN,NaN,NaN
89,부산광역시 연제구,NaN,NaN,NaN,NaN
90,부산광역시 영도구,1.0,NaN,NaN,NaN
91,부산광역시 중구,NaN,NaN,NaN,NaN
143,충청남도 부여군,NaN,NaN,NaN,NaN

In [53]:
num_sports_zeros = num_sports.fillna(0)

In [54]:
num_sports_zeros.isnull().sum()

SGG_NAME                0
SPORTS_FACILITIES_20    0
SPORTS_FACILITIES_21    0
SPORTS_FACILITIES_22    0
SPORTS_FACILITIES_23    0
dtype: int64

In [55]:
num_sports_zeros[num_sports.isnull().any(axis=1)]

,SGG_NAME,SPORTS_FACILITIES_20,SPORTS_FACILITIES_21,SPORTS_FACILITIES_22,SPORTS_FACILITIES_23
59,광주광역시 남구,0.0,0.0,0.0,0.0
67,대구광역시 동구,0.0,0.0,0.0,0.0
69,대구광역시 서구,0.0,0.0,0.0,0.0
71,대구광역시 중구,0.0,0.0,0.0,0.0
74,대전광역시 서구,0.0,0.0,0.0,0.0
80,부산광역시 남구,0.0,0.0,0.0,0.0
82,부산광역시 동래구,0.0,0.0,0.0,0.0
83,부산광역시 부산진구,0.0,0.0,0.0,0.0
84,부산광역시 북구,0.0,0.0,0.0,0.0
87,부산광역시 서구,0.0,0.0,0.0,0.0
89,부산광역시 연제구,0.0,0.0,0.0,0.0
90,부산광역시 영도구,1.0,0.0,0.0,0.0
91,부산광역시 중구,0.0,0.0,0.0,0.0
143,충청남도 부여군,0.0,0.0,0.0,0.0

In [56]:
num_sports_zeros.dtypes

SGG_NAME                 object
SPORTS_FACILITIES_20    float64
SPORTS_FACILITIES_21    float64
SPORTS_FACILITIES_22    float64
SPORTS_FACILITIES_23    float64
dtype: object

In [57]:
num_sports_zeros = num_sports_zeros.astype(dtype='int64', errors='ignore')

In [58]:
num_sports_zeros.dtypes

SGG_NAME                object
SPORTS_FACILITIES_20     int64
SPORTS_FACILITIES_21     int64
SPORTS_FACILITIES_22     int64
SPORTS_FACILITIES_23     int64
dtype: object

In [60]:
num_sports_zeros.to_csv('../processed/체육시설수.csv', index=False)